name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 10
      uses: actions/setup-java@v1
      with:
        java-version: 10
    - name: Build with Maven
      run: mvn package
      
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/labeler@v2
    - name: Deploying to Github Package
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          run: mvn deploy -Dregistry=https://maven.pkg.github.com/mwsu-csmp/gg-game-api --file pom.xml
